version:  "3.8"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=ssh-network
    networks:
      - ssh-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  wetty:
    image: wettyoss/wetty
    container_name: wetty
    labels:
      caddy: ${DOMAIN} 
      caddy.basicauth: /*
      caddy.basicauth.ujstor: ${AUTH_PASSWORD} 
      caddy.reverse_proxy: "{{upstreams 3000}}"
    environment:
      - SSHHOST=ssh-server
      - SSHPORT=2222
      - SSHUSER=${USER}
    networks:
      - ssh-network
    restart: unless-stopped
    depends_on:
      - ssh-server

  ssh-server:
    image: lscr.io/linuxserver/openssh-server
    container_name: ssh-server
    hostname: ssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD_ACCESS=true
      - USER_NAME=${USER}
      - USER_PASSWORD=${USER_PASSWORD}
      - SUDO_ACCESS=true
    networks:
      - ssh-network
    volumes:
      - ssh-config:/config
      - ssh-data:/usr/bin
    restart: unless-stopped

volumes:
  caddy_data:
  ssh-config:
  ssh-data:

networks:
  ssh-network:
    external: true